package com.mailssenger.model;

import com.google.gson.annotations.Expose;

import net.tsz.afinal.annotation.sqlite.Id;

/**
 * the database model for mail
 */
public class MailModel {

	// id is generated by the database and set on the object automatically
	@Id(column = "messageId")
	@Expose
	private String messageId;
	
	private String fromWho;
	private String toWho;
	private String ccWho;
	private String bccWho;
	
	private String sendDate;
	
	@Expose
	private String subject;
	
	@Expose
	private String content;
	@Expose
	private String attachment;
	@Expose
	private String flags;

	private String account;//mutiple account
	
	private String folder;
	private int uid;
	
	public String getMessageId() {
		return messageId;
	}
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}
	public String getFromWho() {
		return fromWho;
	}
	public void setFromWho(String fromWho) {
		this.fromWho = fromWho;
	}
	public String getToWho() {
		return toWho;
	}
	public void setToWho(String toWho) {
		this.toWho = toWho;
	}
	public String getCcWho() {
		return ccWho;
	}
	public void setCcWho(String ccWho) {
		this.ccWho = ccWho;
	}
	public String getBccWho() {
		return bccWho;
	}
	public void setBccWho(String bccWho) {
		this.bccWho = bccWho;
	}
	public String getSendDate() {
		return sendDate;
	}
	public void setSendDate(String sendDate) {
		this.sendDate = sendDate;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getAttachment() {
		return attachment;
	}
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}
	public String getFlags() {
		return flags;
	}
	public void setFlags(String flags) {
		this.flags = flags;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getFolder() {
		return folder;
	}
	public void setFolder(String folder) {
		this.folder = folder;
	}
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}

	
	
}
