package com.mailssenger.model;

import com.google.gson.annotations.Expose;
import com.lidroid.xutils.db.annotation.Column;
import com.lidroid.xutils.db.annotation.Id;

/**
 * @date 20140823
 * the database model for mail
 */
public class MailModel {

	// id is generated by the database and set on the object automatically
	@Expose
	@Id(column = "messageId")
	private String messageId;
	
	/*error: when send a mail to himself, 
	 *the message id of the sent item and received item will be the same
	 *hence will not get the mail into database 
	 */
	
	@Column(column = "formWho")
	private String fromWho;
	
	@Column(column = "toWho")
	private String toWho;
	
	@Column(column = "ccWho")
	private String ccWho;
	
	@Column(column = "bccWho")
	private String bccWho;
	
	@Column(column = "sendDate")
	private String sendDate;
	
	@Expose
	@Column(column = "subject")
	private String subject;
	
	@Expose
	@Column(column = "content")
	private String content;
	
	@Expose
	@Column(column = "attachment")
	private String attachment;
	
	@Expose
	@Column(column = "flags")
	private String flags;

	@Column(column = "account")
	private String account;//mutiple account
	
	@Column(column = "folder")
	private String folder;
	
	@Column(column = "uid")
	private int uid;
	
	public String getMessageId() {
		return messageId;
	}
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}
	public String getFromWho() {
		return fromWho;
	}
	public void setFromWho(String fromWho) {
		this.fromWho = fromWho;
	}
	public String getToWho() {
		return toWho;
	}
	public void setToWho(String toWho) {
		this.toWho = toWho;
	}
	public String getCcWho() {
		return ccWho;
	}
	public void setCcWho(String ccWho) {
		this.ccWho = ccWho;
	}
	public String getBccWho() {
		return bccWho;
	}
	public void setBccWho(String bccWho) {
		this.bccWho = bccWho;
	}
	public String getSendDate() {
		return sendDate;
	}
	public void setSendDate(String sendDate) {
		this.sendDate = sendDate;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getAttachment() {
		return attachment;
	}
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}
	public String getFlags() {
		return flags;
	}
	public void setFlags(String flags) {
		this.flags = flags;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getFolder() {
		return folder;
	}
	public void setFolder(String folder) {
		this.folder = folder;
	}
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	
}
